train: "/kaggle/input/polyp-dataset/data-convert/CVC-300/data/train" 
test: "/kaggle/input/polyp-dataset/data-convert/CVC-300/data/test"
val: "/kaggle/input/polyp-dataset/data-convert/CVC-300/data/val"

nc: 1


names: ['Sign']
